### ISSUE TITLE
build script should default to checking out compatible branch of LiteCore

### ISSUE THREAD

**Issue by snej** [couchbaselabs/cblite#5]
Having the `build.sh` script check out the master branch of LiteCore is risky — every time we change the LiteCore API on the master branch, it breaks the tool's build. (See #4 for an example.)

Since the build script decides which revision of LiteCore to check out, why not have it check out a compatible revision/branch/tag? All it takes is changing the default value of `BRANCH` to something compatible. As we update the tool to work with the latest LiteCore, we can update that value in the same commit.

**Comment by borrrden** [comment]
Could you give an idea of what that branch should be?  Should we create a new one?  The reason it is not pinned is for CI purposes.  These tools should be built for every change in LiteCore so that we can catch things like breaking changes quickly and I didn't want to end up with tons of commits in a row with just "update LiteCore"

**Comment by borrrden** [comment]
Ok I realized halfway through that this could be accomplished in the following way:

1. Add a submodule which will be used by default when the build script is called with no arguments
2. Create a dev branch where breaking API changes can be addressed without affecting the master branch's build that is on the submodule.

After the breaking changes have been addressed, the submodule can be updated before merging the dev branch into master.
